apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: django-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:14
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: jobportal
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              value: "1234"
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgres-storage
      volumes:
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: postgres-pvc